### ISSUE TITLE
v83 request (paid)

### ISSUE THREAD

**Issue by brian-heo** [Francesco149/wxPloiterGMS#3]
hey francesco,

I am having issues compiling (correct dependencies installed) and want to use this for recv blocking. I don't have the time to code it myself anymore but can compensate you quite well if you are interested. For reference, I plan on using it to play around on an old v83 server (can provide more details).

You can contact me on Discord at Brian#3993 or I can provide my email/skype. Hoping to hear back!

**Comment by Francesco149** [comment]
sorry I don't really feel like revisiting this codebase at the moment, but i can imagine why it would be hard to build today as it was written with an old version of wxWidgets and boost
